spring.application.name=verify-service
server.port=8082
spring.data.mongodb.uri=mongodb://localhost:27017/drishti
spring.data.mongodb.database=drishti
management.endpoints.web.exposure.include=health,info
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
ai.service.url=http://localhost:8000
task.service.url=http://localhost:8081
